# Generated by Django 5.1.6 on 2025-02-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='user_id',
        ),
    ]
