# Generated by Django 5.1.6 on 2025-02-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passord',
            new_name='password',
        ),
    ]
